laudos/urls.py
from django.contrib import admin
from django.urls import include, path
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cadastro/', views.sign_up, name='cadastro'),
    path('', include('main.urls')),
    path('social-auth/', include('social_django.urls', namespace='social-auth')),
]

main/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("", views.pag_main.as_view(), name="main_laudos"),
    path("accounts/", include('django.contrib.auth.urls')),
    path("devolucao", views.DevolucaoView.as_view(), name="devolucao"),
    path("manutencao", views.ManutencaoView.as_view(), name="manutencao"),
    path("api-cc/", views.ApiCentroCusto.as_view(), name="api-cc"),
    path("api-laudo-visu/<int:id>/", views.ApiLaudoVisualizacao.as_view(), name='api-laudo-visualizacao'),
    path("edit-man/<int:id>/", views.EditManutencao.as_view(), name="edit-man"),
    path("edit-dev/<int:id>/", views.EditDevolucao.as_view(), name="edit-dev"),
    path("api-edit-cc/<int:id>/", views.ApiEditCC.as_view(), name="edit-cc"),
    path("api-laudo-main", views.ApiLaudoMain.as_view(), name='api-laudo-main'),
    path("api_altera_status/<int:id>/", views.ApiAlteraStatus.as_view(), name='api-status'),
    path("seleciona_unidade", views.SelecionaUnidade.as_view(), name="seleciona_unidade"),
    path("laudos_unidades", views.LaudosUnidades.as_view(), name="laudos_unidades"),
    path("api_laudos_unidades", views.ApiLaudosUnidades.as_view(), name="api_laudos_unidades"),
]

main/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import User

#Model Dados_laudo: Nesta model é guardado informações sobre o local de onde vem o laudo
class Unidade(models.Model):
    nome = models.CharField(max_length=128)

    def __str__(self):
        return self.nome 
    

class Instituto(models.Model):
    nome = models.CharField(max_length=128)
    
    def __str__(self):
        return f'{self.nome}'


#Model centro_custo: Tabela para guardar dados sobre a relação do centro de custo
class RelacaoCentroCusto(models.Model):
    cod_centro_custo = models.CharField(max_length=128, blank=True)
    unid_negocio = models.CharField(max_length=128)
    nome_centro_custo = models.CharField(max_length=128)

    def __str__(self):
        return f'{self.nome_centro_custo}: {self.cod_centro_custo}.{self.unid_negocio}'
    
    class Meta:
        verbose_name = "Relação de Centros de Custo"
        verbose_name_plural = "Relação de Centros de Custo"


class UserProfile(models.Model):
    unidade = models.ForeignKey(Unidade, on_delete=models.CASCADE, null=True, blank=True)
    primeiro_acesso = models.BooleanField(default=True)
    user = models.OneToOneField(
        User, on_delete=models.CASCADE
    )

    def __str__(self):
        return f'O usuario {self.user} esta em seu primeiro acesso'

# Model Ques cria a tabela Laudos no banco de dados, nela existe a diferenciação entre laudo de manutenção ou
# devolução
class Laudos(models.Model):

    tipos = (
        ('', 'Selectione o tipo de equipamento'),
        ('Computador', 'Computador'),
        ('Monitor', 'Monitor'),
        ('Notebook', 'Notebook'),
        ('Switch', 'Switch'),
        ('Projetor', 'Projetor'),
        ('Impressora', 'Impressora')
    )

    status = (
        ('em-progresso', 'Em Progresso'), 
        ('Devolvido-ao-patrimonio', 'Devolvido ao Patrimônio'),
        ('Aguardando-resposta', 'Aguardado Resposta'),
        ('Concluido', 'Concluído')
    )

    tipo_laudo = (
        ('manutencao', 'Manutenção'),
        ('devolucao', 'Devolução')
    )

    baixas = (
        ('', 'Selecione o motivo de devolução'),
        ('sucateamento', 'Baixa por Sucateamento'),
        ('baixo desempenho', 'Baixa por Desempenho')
    )

    nome_solicitante = models.CharField(max_length=128)
    email_solicitante = models.EmailField()
    num_chamado = models.CharField(max_length=14, blank=True, null=True)
    num_sala = models.CharField(max_length=20, blank=True, null=True)
    num_predio = models.IntegerField()
    num_ramal = models.IntegerField()
    setor = models.CharField(max_length=128)
    tipo_equip = models.CharField(max_length=128, choices=tipos)
    num_serie = models.CharField(max_length=128)
    patrimonio = models.CharField(max_length=14, blank=True, null=True)
    marca = models.CharField(max_length=55)
    modelo = models.CharField(max_length=55)
    observacoes = models.TextField()
    status = models.CharField(max_length=128, choices=status)
    tipo_laudo = models.CharField(max_length=128, choices=tipo_laudo)
    tipo_baixa = models.CharField(max_length=128, choices=baixas, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.RESTRICT)
    unidade = models.ForeignKey(Unidade, on_delete=models.RESTRICT)
    instituto = models.ForeignKey(Instituto, on_delete=models.RESTRICT)
    centro_custo = models.ForeignKey(RelacaoCentroCusto, on_delete=models.RESTRICT, null=True, blank=True)
    criacao = models.DateTimeField(auto_now_add=True)
    

    class Meta:
        verbose_name = 'Laudos'
        verbose_name_plural = 'Laudos'


    def __str__(self):
        return f'Laudo do tipo {self.tipo_laudo} com patrimônio - {self.patrimonio} e número de serie - {self.num_serie} foi criado {self.criacao}'

main/forms.py
from django import forms
from .models import Laudos
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class FormLaudoDevolucao(forms.ModelForm):

    class Meta:
        model = Laudos
        fields = ['nome_solicitante', 'email_solicitante', "unidade", "instituto", "setor",
                  "num_chamado", "num_predio", "num_sala", "num_ramal", "tipo_equip", "status",
                  "num_serie", "patrimonio", "marca", "modelo", "tipo_baixa", "observacoes",
                  "user", "tipo_laudo"]




class FormLaudoManutencao(forms.ModelForm):

    class Meta:
        model = Laudos
        fields = ["nome_solicitante", "email_solicitante", "unidade", "instituto", "setor",
                "num_chamado", "num_predio", "num_sala", "num_ramal", "tipo_equip", "num_serie",
                "patrimonio", "marca", "modelo", "observacoes", "centro_custo", "user", "status",
                "tipo_laudo"
        ]


class SignUpForm(UserCreationForm):
    password1 = forms.CharField(label="Senha", widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label="Confirme a senha", widget=forms.PasswordInput(attrs={'class':'form-control'}))
    email = forms.EmailField(label="E-mail",widget=forms.TextInput(attrs={'class':'form-control'}), required=True)
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']
        labels = {'email': 'E-mail', 'last_name': 'Sobrenome', 'first_name': 'Nome', 'password1': 'Senha', 'password2': 'Confirme a senha'}
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'first_name': forms.TextInput(attrs={'class':'form-control'}),
            'last_name': forms.TextInput(attrs={'class':'form-control'}),
        }

main/views.py
from typing import Any, Dict
from django.contrib import messages
from django.shortcuts import redirect, render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.views.generic import TemplateView, View,ListView
from .models import *
from .forms import FormLaudoDevolucao, FormLaudoManutencao, SignUpForm
import json as simplejson
from .serializers import *
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.db.models import Q
from datetime import datetime


# View onde o usuario ve o datatables onde tem a informação de todos os laudos, é uma api onde se limita quantos laudos serão enviados ao 
# front-end, tem uma função de filtragem e envia dados do banco em formato de JSON
class ApiLaudoMain(LoginRequiredMixin, View):
    

    #Função que conta quantos laudos existem no banco
    def numero_elementos(self, request):
        laudos = Laudos.objects.filter(unidade=request.user.userprofile.unidade).count()
        return laudos
    

    #Função de envio para visualização dos dados    
    def get(self, request):

        
        #Variaveis pegas do front-end especificamente do datatables
        inicio = int(request.GET.get('inicio'))
        fim = int(request.GET.get('limite'))
        search = request.GET.get('filtro')
        total = 0
    
        user_profile = request.user.userprofile
        

        if user_profile.primeiro_acesso == True:
            return redirect('seleciona_unidade')

        if search:
            filtro = Q(num_chamado__icontains=search) | Q(unidade__nome__icontains=search) | Q(patrimonio__icontains=search) | Q(user__last_name__icontains=search) | Q(status__icontains=search)
            
            laudos = Laudos.objects.filter(unidade=request.user.userprofile.unidade).filter(filtro)[inicio: inicio+fim]
            
            total = Laudos.objects.filter(unidade=request.user.userprofile.unidade).filter(filtro).count()
        
        # Quando não tem pesquisa envia os dados separadamente
        else:
            laudos = Laudos.objects.filter(unidade=request.user.userprofile.unidade).order_by('-criacao')[inicio: inicio+fim]
            total = Laudos.objects.filter(unidade=request.user.userprofile.unidade).count()

        # Serializando para enviar em JSON
        laudos_ser = LaudoSerializer(laudos, many=True)

        # dicionario das informações a serem enviadas
        data = {
            'objects': laudos_ser.data,
            'length': self.numero_elementos(request),
            'total': total
        }

        

        # Envio dessas informações em JSON
        return JsonResponse({'data': data})
        



#View de visualização da pagina html
class pag_main(LoginRequiredMixin, TemplateView):

    def get(self, request):
        usuario_logado = request.user

        user_profile = request.user.userprofile

        if user_profile.primeiro_acesso == True:
            return redirect('seleciona_unidade')

        return render(request, 'main_templates/main_laudos.html', {'usuario': usuario_logado})
    


class ApiLaudosUnidades(LoginRequiredMixin, View):

    def numero_elementos(self, request):
        laudos = Laudos.objects.all().count()
        return laudos

    def get(self, request):

        #Variaveis pegas do front-end especificamente do datatables
        inicio = int(request.GET.get('inicio'))
        fim = int(request.GET.get('limite'))
        search = request.GET.get('filtro')
        total = 0

        user_profile = request.user.userprofile

        if user_profile.primeiro_acesso == True:
            return redirect('seleciona_unidade')
        
        if search:
            filtro = Q(num_chamado__icontains=search) | Q(unidade__nome__icontains=search) | Q(patrimonio__icontains=search) | Q(user__last_name__icontains=search) | Q(status__icontains=search)
            
            laudos = Laudos.objects.all().filter(filtro)[inicio: inicio+fim]
            
            total = Laudos.objects.all().filter(filtro).count()
        
        # Quando não tem pesquisa envia os dados separadamente
        else:
            laudos = Laudos.objects.all().order_by('-criacao')[inicio: inicio+fim]
            total = Laudos.objects.all().count()

        # Serializando para enviar em JSON
        laudos_ser = LaudoSerializer(laudos, many=True)

        # dicionario das informações a serem enviadas
        data = {
            'objects': laudos_ser.data,
            'length': self.numero_elementos(request),
            'total': total
        }

        return JsonResponse({'data': data})




class LaudosUnidades(PermissionRequiredMixin, View):

    permission_required = 'auth.ST_LAUDOS_ADD_DEVOLUCAO'

    def get(self, request):

        usuario_logado = request.user

        user_profile = request.user.userprofile

        if user_profile.primeiro_acesso == True:
            return redirect('seleciona_unidade')

        return render(request, 'main_templates/laudos_unidades.html', {'usuario': usuario_logado})




class DevolucaoView(PermissionRequiredMixin, View):
    template_name = 'main_templates/devolucao.html'

    permission_required = 'auth.ST_LAUDOS_ADD_DEVOLUCAO'
    
    #Metodo get que me retorna o formulario na pagina
    def get(self, request):

        user_profile = request.user.userprofile
        if user_profile.primeiro_acesso == True:
            return redirect('seleciona_unidade')

        form = FormLaudoDevolucao()
        form.user = request.user
        return render(request, 'main_templates/devolucao.html', {'form': form})    
    
    def post(self, request):
        form = FormLaudoDevolucao(request.POST)

        if form.is_valid():
            devolucao = form.save(commit=False)
            if not devolucao.num_sala:
                devolucao.num_sala = 0

            if devolucao.setor is None:
                devolucao.departamento = 'Não Vinculado'

            if devolucao.num_chamado is None or devolucao.num_chamado == "0":
                devolucao.num_chamado = 'Interno CRC'

            if devolucao.patrimonio is None or devolucao.patrimonio == "0":
                devolucao.patrimonio = 'Ausente' 

            devolucao.save()
            messages.success(request, 'Laudo de Devolução criado com sucesso')
            return redirect(reverse('main_laudos'))
        

class ManutencaoView(PermissionRequiredMixin, View):

    permission_required = 'auth.ST_LAUDOS_ADD_MANUTENCAO'

    def get(self, request):

        user_profile = request.user.userprofile
        if user_profile.primeiro_acesso == True:
            return redirect('seleciona_unidade')

        form = FormLaudoManutencao()
        form.user = request.user
        return render(request, 'main_templates/manutencao.html', {'form': form})

    def post(self, request):
        form = FormLaudoManutencao(request.POST)
       
        if form.is_valid():
            manutencao = form.save(commit=False)
            if not manutencao.num_sala:
                manutencao.num_sala = 0

            if manutencao.setor is None:
                manutencao.departamento = 'Não Vinculado'

            if manutencao.num_chamado is None or manutencao.num_chamado == "0":
                manutencao.num_chamado = 'Interno CRC'

            if manutencao.patrimonio is None or manutencao.patrimonio == "0":
                manutencao.patrimonio = 'Ausente'     
            manutencao.save()
            messages.success(request, 'Laudo de Manutenção criado com sucesso')
            return redirect(reverse('main_laudos'))
        
    

   
class ApiCentroCusto(PermissionRequiredMixin, View):

    permission_required = 'auth.ST_LAUDOS_ADD_CENTRO_CUSTO'

    def post(self, request):
        nome_cc = request.POST.get('nome_cc')
        cod_cc = request.POST.get('cod_cc')
        unidade_negocio = request.POST.get('unidade_negocio')

        if nome_cc and cod_cc and unidade_negocio:
            cc, created = RelacaoCentroCusto.objects.get_or_create(cod_centro_custo=cod_cc, unid_negocio=unidade_negocio, nome_centro_custo=nome_cc)

            cc = {
                'id': cc.id,
                'cod_centro_custo': cc.cod_centro_custo,
                'unid_negocio': cc.unid_negocio,
                'created': created,
                'nome_centro_custo': cc.nome_centro_custo
            }
            
            return JsonResponse({'res': 'Criado', "cc": simplejson.dumps(cc)})
        
        else:
            return JsonResponse({'res': 'Erro campos criados em branco'}, status=400)
        
    def get(self, request):
        relacao_cc = RelacaoCentroCusto.objects.all()
        serializers = RelacaoCCSerializer(relacao_cc, many=True)

        return JsonResponse({'res': 'criado', "cc": serializers.data})
    
    
class ApiEditCC(PermissionRequiredMixin, View):

    permission_required = 'auth.ST_LAUDOS_EDIT_CENTRO_CUSTO'

    def post(self, request, id):
        try:        

            cc = RelacaoCentroCusto.objects.get(pk=id)
            cc.nome_centro_custo = request.POST.get('nome_cc')
            cc.cod_centro_custo = request.POST.get('cod_cc')
            cc.unid_negocio = request.POST.get('unid_cc')

            cc.save()

            cc_serializer = RelacaoCCSerializer(cc)
            

            return JsonResponse({'res': 'Editado com sucesso', 'cc': cc_serializer.data})
        except:
            return HttpResponse({'res': 'Erro ao editar centro de custo'}, status=400)



class ApiLaudoVisualizacao(LoginRequiredMixin, View):
    def get(self, request, id):
        laudos = Laudos.objects.get(pk=id)
        serializers = LaudoSerializer(laudos)
        
        return JsonResponse({"status": "Sucess", "data": serializers.data})
    

# classe que edita o laudo de manutanção
class EditManutencao(PermissionRequiredMixin, View):

    permission_required = 'auth.ST_LAUDOS_EDIT_LAUDO'

main/templates/main_templates/confirma-status-dev.html
{% load static %}
{% csrf_token %}
<div class="modal modal-blur fade" id="confirma-status-dev" tabindex="-1" style="display: none;" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Alteração Status De Devolução</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Você tem a intenção de atualizar o status de <b>"Em Progresso"</b> para <b>"Devolvido ao Patrimônio"</b> a fim de encerrar o laudo?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn me-auto" data-bs-dismiss="modal">Não, cancelar</button>
        <button type="button" id="confirma-dev" class="btn btn-primary" data-bs-dismiss="modal">Sim, encerrar</button>
      </div>
    </div>
  </div>
</div>


<script>

  $(() => {
    $.ajaxSetup({
        headers: {
            "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
        }
    })
  })

</script>

main/templates/main_templates/devolucao.html
{% extends 'main_templates/base_laudos.html' %}

{% block content %}

<style>
    .title-form {
        display: flex;
        justify-content: center;
    }


    .botoes {
        display: flex;
        justify-content: space-between;
    }

    input[type=number]::-webkit-inner-spin-button,
    input[type=number]::-webkit-outer-spin-button {
        -webkit-appearance: none;
        margin: 0;
    }

    .readonly_select{
        color: grey;
        pointer-events: none;
    }
</style>

<div style="display: none" id="unidade_user" >
    {{request.user.userprofile.unidade}}
</div>

<form method="POST" action="{% url 'devolucao' %}">
    {% csrf_token %}
    {{form.user}}
    {{form.tipo_laudo}}
    <h1 class="title-form">Processo de Devolução de Bem</h1>
    <div class="page-body">
        <div class="container-xl">
            <div class="card">
                <div class="card-body">
                    <h1 class="title-form">Laudo Técnico</h1>
                    <div class="row row-cards">
                        <div class="col-sm-6 col-md-6">
                            <label class="form-label required">Nome do Solicitante</label>
                            <div class="input-icon">
                                <span class="input-icon-addon">
                                    <!-- Download SVG icon from http://tabler-icons.io/i/user -->
                                    <svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24"
                                        viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                        stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                        <path d="M8 7a4 4 0 1 0 8 0a4 4 0 0 0 -8 0"></path>
                                        <path d="M6 21v-2a4 4 0 0 1 4 -4h4a4 4 0 0 1 4 4v2"></path>
                                    </svg>
                                </span>
                                {{form.nome_solicitante}}
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-6">
                            <div class="md-3 ">
                                <label class="form-label required">Email do Solicitante</label>
                                <div class="input-icon ">
                                    <span class="input-icon-addon">
                                        <!-- Download SVG icon from http://tabler-icons.io/i/user -->
                                        <svg xmlns="http://www.w3.org/2000/svg"
                                            class="icon icon-tabler icon-tabler-mail" width="24" height="24"
                                            viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none"
                                            stroke-linecap="round" stroke-linejoin="round">
                                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                            <path
                                                d="M3 7a2 2 0 0 1 2 -2h14a2 2 0 0 1 2 2v10a2 2 0 0 1 -2 2h-14a2 2 0 0 1 -2 -2v-10z">
                                            </path>
                                            <path d="M3 7l9 6l9 -6"></path>
                                        </svg>
                                    </span>
                                    {{form.email_solicitante}}
                                </div>
                            </div>
                        </div>
                        <div class="col-sm-4 col-md-4">
                            <div class="md-3">
                                <label class="form-label required">Unidade</label>
                                {{form.unidade}}
                            </div>
                        </div>
                        <div class="col-sm-4 col-md-4">
                            <div class="md-3">
                                <label class="form-label required">Instituto</label>
                                {{form.instituto}}
                            </div>
                        </div>
                        <div class="col-sm-4 col-md-4">
                            <div class="md-3">
                                <label class="form-label">Setor</label>
                                {{form.setor}}
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-6">
                            <div class="md-3">
                                <label class="form-label ">Número do Chamado</label>
                                {{form.num_chamado}}
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-6">
                            <div class="md-3">
                                <label class="form-label required">Prédio</label>
                                {{form.num_predio}}
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-6">
                            <div class="md-3">
                                <label class="form-label">Sala</label>
                                {{form.num_sala}}
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-6">
                            <div class="md-3">
                                <label class="form-label required">Ramal</label>
                                {{form.num_ramal}}
                            </div>
                        </div>
                    </div>
                    <h1 class="title-form" style="margin-top: 20px;">Dados Do Equipamento</h1>
                    <div class="row row-cards">
                        <div class="col-sm-6 col-md-6">
                            <div class="md-3">
                                <label class="form-label required">Equipamento</label>
                                {{form.tipo_equip}}
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-6">
                            <div class="md-3">
                                <label class="form-label required">Status</label>
                                {{form.status}}
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-6">
                            <div class="md-3">
                                <label class="form-label required">Número de Seríe</label>
                                {{form.num_serie}}
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-6">
                            <div class="md-3">
                                <label class="form-label">Patrimônio</label>
                                {{form.patrimonio}}
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-6">
                            <div class="md-3">
                                <label class="form-label required">Marca</label>
                                {{form.marca}}
                            </div>
                        </div>
                        <div class="col-sm-6 col-md-6">
                            <div class="md-3">
                                <label class="form-label required">Modelo</label>
                                {{form.modelo}}
                            </div>
                        </div>
                        <div class="md-3">
                            <label class="form-label required">Tipo Devolução</label>
                            {{form.tipo_baixa}}
                        </div>
                        <div class="mb-3">
                            <label class="form-label required">Observações</label>
                            {{form.observacoes}}
                        </div>
                    </div>
                    <div class="botoes">
                        <div class="py-3">
                            <a href="{% url 'main_laudos' %}" class="btn btn-primary w-150">
                                Voltar
                            </a>
                        </div>
                        <div class="py-3">
                            <button type="submit" class="btn btn-success w-100">
                                Adicionar Laudo
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
<script>

    $(() => {
        $.ajaxSetup({
            headers: {
                "X-CSRFToken": $('[name=csrfmiddlewaretoken]').val()
            }
        })
        
    })


    $('#id_user option[value="{{request.user.id}}"]').prop("selected", true)
    $('#id_user').css('display', 'none')

    $('#id_tipo_laudo option[value="devolucao"]').prop("selected", true)
    $('#id_tipo_laudo').css('display', 'none')

    

    $('input').addClass('form-control')
    $('select').addClass('form-select')
    $('textarea').addClass('form-control')

    $('#id_nome_solicitante').attr('placeholder', 'Nome do Solicitante')
    $('#id_email_solicitante').attr('placeholder', 'Email do Solicitante')
    $('#id_num_chamado').attr('placeholder', 'Número do CSC')
    $('#id_num_ramal').attr('placeholder', 'Número do Ramal')
    $('#id_num_predio').attr('placeholder', 'Número do Prédio')
    $('#id_num_sala').attr('placeholder', 'Número da Sala')
    $('#id_num_serie').attr('placeholder', 'Número de Série')
    $('#id_patrimonio').attr('placeholder', 'Número do Patrimônio')
    $('#id_marca').attr('placeholder', 'Marca do Equipamento')
    $('#id_modelo').attr('placeholder', 'Modelo do Equipamento')
    $('#id_observacoes').attr('style', 'height: 100px;')
    $('#id_observacoes').attr('placeholder', 'Observações e testes realizados')
    $('#id_setor').attr('placeholder', 'Nome Setor')

    // adicionando um "placeholder" aos selects e tirando a opção do usuario selecionar o primeiro select 
    $('#id_unidade option:first').text('Selecione uma Unidade')
    $('#id_unidade option:first').prop("disabled", true)
    $('#id_unidade').addClass('readonly_select')
    $('#id_instituto option:first').text('Selecione um Instituto')
    $('#id_instituto option:first').prop("disabled", true)
    $('#id_status option:first').text('Selecione o status do laudo')
    $('#id_status option:first').prop("disabled", true)

    $('#id_status option:eq(3)').remove()
    $('#id_status option:eq(4)').remove()
    $('#id_status option:last').remove()
    

    $('#id_tipo_equip option:first').prop("disabled", true)
    $('#id_tipo_baixa option:first').prop("disabled", true)

    $('#id_num_chamado').attr('type', 'number')
    $('#id_patrimonio').attr('type', 'number')
    
    // função para limitar a quantidade de digitos que o usuario pode digitar no campo numero chamado (8 digitos)
    $('#id_num_chamado').on('input', function() {
        let maximo = 8
        if(this.value.length > maximo){
            this.value = this.value.slice(0, maximo)
        }
    })

    // função para limitar a quantidade de digitos que o usuario pode digitar no campo patrimonio (14 digitos)
    $('#id_patrimonio').on('input', function() {
        let maximo = 14
        if (this.value.length > maximo){
            this.value = this.value.slice(0, maximo)
        }
    })

    // Inicio do select onde o usuario pode digitar para filtrar o valor
   
    
    //filtro campo unidade
    

    //filtro campo tipo de equipamento
    document.addEventListener("DOMContentLoaded", function () {
        var el;
    	window.TomSelect && (new TomSelect(el = document.getElementById('id_tipo_equip'), {
    		copyClassesToDropdown: false,
    		dropdownParent: 'body',
    		controlInput: '<input>',
    		
    	}));
    });

    //filtro campo insituto
    document.addEventListener("DOMContentLoaded", function () {
    	var el;
    	window.TomSelect && (new TomSelect(el = document.getElementById('id_instituto'), {
    		copyClassesToDropdown: false,
    		dropdownParent: 'body',
    		controlInput: '<input>',
    		render:{
    			item: function(data,escape) {
    				if( data.customProperties ){
    					return '<div><span class="dropdown-item-indicator">' + data.customProperties + '</span>' + escape(data.text) + '</div>';
    				}
    				return '<div>' + escape(data.text) + '</div>';
    			},
    			option: function(data,escape){
    				if( data.customProperties ){
    					return '<div><span class="dropdown-item-indicator">' + data.customProperties + '</span>' + escape(data.text) + '</div>';
    				}
    				return '<div>' + escape(data.text) + '</div>';
    			},
    		},
    	}));
    });
    // final da função dos selects


    let unidade_usuario = $('#unidade_user').text().trim()
    
    
    
    $('#id_unidade option').each(function() {
        let select = $(this).text().trim()
        if (select == unidade_usuario) {
            $(this).prop('selected', true)
        }
    })
    
    

</script>



{% endblock %}